### ISSUE TITLE
Roadmap Oct'17 - Dec'17

### ISSUE THREAD

**Issue by SerafimArts** [railt/railt#22]
## Reflection

- [x] Merge `railt/parser` and `railt/reflection` into single package.
- [x] Remove `railt/support` package.
- [x] **Release alpha 1** (`composer require railt/compiler 0.0.1`)
- [x] Fix and improve arguments LSP (Reflection).
- [x] To get rid of checks of a status of the builder and to take out in validation from the outside (visitor?).
- [x] Remove "[extend](https://github.com/railt/railt/blob/77aa9b14090f557fe17e3c5f529affd7c5b339f9/src/Railt/Reflection/Contracts/Processable/ExtendDefinition.php)" from visible types and make preprocessing kernel (required for future additional features like #21 ).
- [x] Exceptions improvement: https://github.com/railt/railt/issues/23
- [x] Add type verifications.
- [x] Types inheritance bugfixes.
- [x] ~Waiting for https://github.com/hoaproject/Compiler/pull/76~
- [ ] ~Waiting for https://github.com/hoaproject/Compiler/pull/79~
- [ ] ~Waiting for a new release of hoa/compiler~ (forked into: https://github.com/railt/parser)
- [x] **Release 1.0**

## Webonyx builder

- [x] Implement the base [Webonyx](https://github.com/webonyx/graphql-php) support
- [x] Add support of `Field` Type
- [x] Add support of `Argument` Type
- [x] Add support of `Schema `Type
- [x] Add support of `Object` Type
- [x] Add support of `Interface` Type
- [ ] Add support of `Union` Type
- [x] Add support of `Directive` Type
- [x] Add support of `Scalar` Type
- [ ] Add support of `Enum` Type
- [ ] Add support of `Input` Type
- [x] Add type invocations base hooks support

**Comment by SerafimArts** [comment]
A little benchmarks Compiler 0.0.1 vs 0.0.2 + (No Cache vs Filesystem) + (PHP 7.1 vs PHP 7.2)

![image](https://user-images.githubusercontent.com/2461257/32658287-5085aafa-c62a-11e7-9bda-1bb4827e9ac4.png)

**Comment by Hywan** [comment]
Neat :-).

How to collect those numbers?

**Comment by SerafimArts** [comment]
@Hywan https://grafana.com/ =)

**Comment by SerafimArts** [comment]
In order not to depend on third-party releases, the component `hoa/compiler` was forked into `railt/parser`.  This decision required the use of a dual license: [MIT + New BSD](https://github.com/railt/railt/blob/master/LICENSE.md)

In addition, this solution has allowed us to get rid of the Hoa ecosystem (sry @Hywan %) ), remove unnecessary dependencies that interfere with the static analysis of the code and start refactoring the source code, taking into account the PSR-12 standards.

**Comment by Hywan** [comment]
Can I see the PR and understand the why of this decision :-)?

**Comment by SerafimArts** [comment]
PR is not available (is absent). I just want to experiment with the code and rewrite it, making it more readable. In addition, I can make releases with kernel fixes immediately on the spot, and not expect someone.

If the result of the work is pleasant, then I can merge back.

**Comment by Hywan** [comment]
I would love to get it back ;-). Anyway, ping me if you need help, I'm glad to help.

**Comment by SerafimArts** [comment]
@Hywan I do https://github.com/hoaproject/Compiler/pull/79#issuecomment-343646583 :D

**Comment by SerafimArts** [comment]
Some developments have been made, but there will not be a release. The rest has lowered the priority. I think it's worth doing monthly roadmaps, they're easier to plan)

Released:
1) Reflection: https://github.com/railt/reflection/releases/tag/1.0.1
2) Compiler: https://github.com/railt/compiler/releases/tag/1.0.3
3) Parser (based on Hoa Compiler): https://github.com/railt/parser/releases/tag/1.0.1

If there are grammatical errors in the release of notices - please understand and forgive)
