### ISSUE TITLE
Roadmap Jan'18 - ...

### ISSUE THREAD

**Issue by SerafimArts** [railt/railt#63]
# Roadmap

### Features:

- [x] https://github.com/railt/railt/issues/40: Directives "DOCUMENT" location
- [x] https://github.com/railt/railt/issues/43: Single types dictionary
- [ ] https://github.com/railt/railt/issues/47: Extending Enums
- [ ] https://github.com/railt/railt/issues/38: Nesting Interfaces

### Bugfixes:

- [x] https://github.com/railt/railt/issues/87: Directive invocation argument value is empty when it's an Input.
- [x] https://github.com/railt/railt/issues/86: Type collation does not work with directive invocation.

# Progress

- Acceleration of the work of the Lexer more than 150 times.
- New AST structure.
- Error correction with type inheritance of another type.
- New CallStack.
- The compiler has removed the dictionary methods.
- Added Directives "DOCUMENT" location (`directive @xxx on DOCUMENT`).
- Added validation of location directives.
- Added validation of the naming of the locations of directives.
- Correction of cloning of a CallStack (empty trace in recursive exceptions).
- Correction of the exception position in the source code from a variable (not from a file).
- Simplify exclusion code (a separate class of CallStack renderer is created).
- Added a CallStack Observer class.
- A single dictionary of generalized types is created.
- Significantly improved code and structure of tests.
- Added support for recursive build of invokation types.
- The possibility of schema naming was added (`schema XXX {}`).
- Added support for multiple directives of the same name (`type Some @directive @directive @directive {}`).
- Fix error message with recursive autoload (An attempt to load an invalid type that contains a non-existent type).
- Correcting validation of arguments of directives and objects.

[← Oct'17 - Dec'17](https://github.com/railt/railt/issues/22)
